export const strapiApiPath = {
  ABOUT: "/about",
  LAYOUT: "/layout",
  SERVICE_LAYOUT: "/service-layout",
  COMPANY_PROFILE: "/company-profile",
  FAQ_PAGE: "/faq-page",
  BOARDS: "/boards",
  PROJECTS: "/projects",
  SERVICES: "/services",
  BOARD_ITEMS: "/list-items",
  BANNERS: "/banners",
  ABOUT_SECTION: "/about-section",
  ABOUT_SECTION_HOME: "/about-section-home",
  ABOUT_HISTORY_SECTION: "/history-section",
  SLIDER_IMAGES: "/slider-images",
  TEAM: "/teams",
  TESTIMONIALS: "/testimonials",
  PROJECT_PAGE: "/project-page",
  SERVICE_PAGE: "/service-page",
  CONTACT_US: "/contact-us",
  QUOTATION_FORM: "/quotation-form",
  CONTACT_FORM: "/contact-form",
  MEDIA: '/mediaa',
  WEB_PAGES: '/webpages?filters[slug][$eq]=home&populate[meta_info][populate][keywords]=true&populate[banner]=true&populate[boardA]=true&populate[boardB]=true&populate[boardC]=true&populate[boardD]=true&populate[boardE]=true&populate[boardF]=true&populate[boardG]=true&populate[service_section]=true&populate[project_section]=true&populate[ctaA]=true&populate[ctaB]=true&populate[ctaC]=true&populate[testimonial]=true&populate[faq]=true',
};
