export const strapiApiPath = {
  ABOUT: "/about",
  LAYOUT: "/layout",
  SERVICE_LAYOUT: "/service-layout",
  COMPANY_PROFILE: "/company-profile",
  FAQ_PAGE: "/faq-page",
  BOARDS: "/boards",
  PROJECTS: "/projects",
  SERVICES: "/services",
  BOARD_ITEMS: "/list-items",
  BANNERS: "/banners",
  ABOUT_SECTION: "/about-section",
  ABOUT_SECTION_HOME: "/about-section-home",
  ABOUT_HISTORY_SECTION: "/history-section",
  SLIDER_IMAGES: "/slider-images",
  TEAM: "/teams",
  TESTIMONIALS: "/testimonials",
  PROJECT_PAGE: "/project-page",
  SERVICE_PAGE: "/service-page",
  CONTACT_US: "/contact-us",
  QUOTATION_FORM: "/quotation-form",
  CONTACT_FORM: "/contact-form",
  MEDIA: '/mediaa'
};
