export const strapiApiPath = {
  ABOUT: "/about",
  LAYOUT: "/layout",
  COMPANY_PROFILE: "/company-profile",
  FAQ_PAGE: "/faq-page",
  BOARDS: "/boards",
  PROJECTS: "/projects",
  BOARD_ITEMS: "/list-items",
  BANNERS: "/banners",
  ABOUT_SECTION: "/about-section",
  ABOUT_SECTION_HOME: "/about-section-home",
  ABOUT_HISTORY_SECTION: "/history-section",
  SLIDER_IMAGES: "/slider-images",
  TEAM: "/teams",
  TESTIMONIALS: "/testimonials",
  PROJECT_PAGE: "/project-page",
};
