export const brands = [];

export const boards = [
  {
    id: 1,
    title: null,
    button: null,
    slug: "main-board-1",
    subtitle: null,
    published_at: "2023-11-14T03:11:10.891Z",
    created_at: "2023-11-14T03:11:08.367Z",
    updated_at: "2023-11-14T03:11:10.965Z",
    items: [
      {
        id: 1,
        title: "Quality Materials",
        content: "You can expect superior quality solar modules.",
        button: null,
        link: null,
        slug: "main-board-1",
        published_at: "2023-11-14T02:30:37.001Z",
        created_at: "2023-11-14T02:30:31.957Z",
        updated_at: "2023-11-14T03:18:11.039Z",
        background_image: null,
        media: {
          id: 72,
          name: "features_icon01.svg",
          alternativeText: "",
          caption: "",
          width: 39,
          height: 41,
          formats: null,
          hash: "features_icon01_21591fe95c",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 14.74,
          url: "/uploads/features_icon01_21591fe95c.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:05.214Z",
          updated_at: "2023-11-12T17:21:05.300Z",
        },
      },
      {
        id: 2,
        title: "Expert Engineer",
        content:
          "Dedicated team of certified installers performing calculations, analysis and designs for your ease.",
        button: null,
        link: null,
        slug: "main-board-1",
        published_at: "2023-11-14T02:42:19.525Z",
        created_at: "2023-11-14T02:41:51.294Z",
        updated_at: "2023-11-14T03:17:49.914Z",
        background_image: null,
        media: {
          id: 73,
          name: "features_icon02.svg",
          alternativeText: "",
          caption: "",
          width: 50,
          height: 39,
          formats: null,
          hash: "features_icon02_ea56f47253",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 4.29,
          url: "/uploads/features_icon02_ea56f47253.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:05.426Z",
          updated_at: "2023-11-12T17:21:05.490Z",
        },
      },
      {
        id: 3,
        title: "Quality Maintenance",
        content:
          "Moreover, an impeccable after-sale service is our selling proposition.",
        button: null,
        link: null,
        slug: "main-board-1",
        published_at: "2023-11-14T02:43:22.159Z",
        created_at: "2023-11-14T02:43:18.988Z",
        updated_at: "2023-11-14T03:18:00.884Z",
        background_image: null,
        media: {
          id: 74,
          name: "features_icon03.svg",
          alternativeText: "",
          caption: "",
          width: 38,
          height: 38,
          formats: null,
          hash: "features_icon03_a1ca7b6e98",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 5.85,
          url: "/uploads/features_icon03_a1ca7b6e98.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:05.575Z",
          updated_at: "2023-11-12T17:21:05.623Z",
        },
      },
    ],
  },
  {
    id: 2,
    title: "What We Do",
    button: null,
    slug: "services",
    subtitle: "Our Services Areas",
    published_at: "2023-11-14T03:13:39.893Z",
    created_at: "2023-11-14T03:12:25.528Z",
    updated_at: "2023-11-18T18:02:50.945Z",
    items: [
      {
        id: 6,
        title: "SOLAR WATER PUMPING SYSTEM",
        content:
          "The system operates on power generated using solar PV (photovoltaic) system.",
        button: null,
        link: "/services-details/solar-water-pumping-system/",
        slug: "services",
        published_at: "2023-11-14T03:17:28.137Z",
        created_at: "2023-11-14T03:17:24.302Z",
        updated_at: "2023-11-18T17:38:49.458Z",
        background_image: {
          id: 253,
          name: "img-one.jpg",
          alternativeText: "",
          caption: "",
          width: 276,
          height: 193,
          formats: {
            thumbnail: {
              name: "thumbnail_img-one.jpg",
              hash: "thumbnail_img_one_17b12fa848",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 223,
              height: 156,
              size: 13.1,
              path: null,
              url: "/uploads/thumbnail_img_one_17b12fa848.jpg",
            },
          },
          hash: "img_one_17b12fa848",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 19.92,
          url: "/uploads/img_one_17b12fa848.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:13.629Z",
          updated_at: "2023-11-12T17:26:13.685Z",
        },
        media: {
          id: 87,
          name: "services_icon01.svg",
          alternativeText: "",
          caption: "",
          width: 39,
          height: 39,
          formats: null,
          hash: "services_icon01_766ac6a7ca",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 1.77,
          url: "/uploads/services_icon01_766ac6a7ca.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:09.995Z",
          updated_at: "2023-11-12T17:21:10.089Z",
        },
      },
      {
        id: 7,
        title: "ON-GRID SOLAR SYSTEM",
        content:
          "On-grid or grid-tie solar systems are by far the most common & widely used.",
        button: null,
        link: "/services-details/On-Grid-Solar-PV-System/",
        slug: "services",
        published_at: "2023-11-14T03:19:33.096Z",
        created_at: "2023-11-14T03:19:28.524Z",
        updated_at: "2023-11-18T17:38:29.787Z",
        background_image: {
          id: 255,
          name: "img-two.jpg",
          alternativeText: "",
          caption: "",
          width: 276,
          height: 193,
          formats: {
            thumbnail: {
              name: "thumbnail_img-two.jpg",
              hash: "thumbnail_img_two_09851b62f5",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 223,
              height: 156,
              size: 10.52,
              path: null,
              url: "/uploads/thumbnail_img_two_09851b62f5.jpg",
            },
          },
          hash: "img_two_09851b62f5",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 15.3,
          url: "/uploads/img_two_09851b62f5.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:14.684Z",
          updated_at: "2023-11-12T17:26:14.792Z",
        },
        media: {
          id: 85,
          name: "services_icon02.svg",
          alternativeText: "",
          caption: "",
          width: 62,
          height: 33,
          formats: null,
          hash: "services_icon02_72d8b4b668",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 5.2,
          url: "/uploads/services_icon02_72d8b4b668.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:09.250Z",
          updated_at: "2023-11-12T17:21:09.367Z",
        },
      },
      {
        id: 8,
        title: "OFF-GRID SOLAR SYSTEM",
        content: "An off-grid system is not connected to the electricity grid.",
        button: null,
        link: "/services-details/Off-Grid-Solar-PV-System/",
        slug: "services",
        published_at: "2023-11-14T03:26:04.730Z",
        created_at: "2023-11-14T03:25:15.389Z",
        updated_at: "2023-11-18T17:38:21.389Z",
        background_image: {
          id: 254,
          name: "img-three.jpg",
          alternativeText: "",
          caption: "",
          width: 276,
          height: 193,
          formats: {
            thumbnail: {
              name: "thumbnail_img-three.jpg",
              hash: "thumbnail_img_three_c9502ebbd9",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 223,
              height: 156,
              size: 11.42,
              path: null,
              url: "/uploads/thumbnail_img_three_c9502ebbd9.jpg",
            },
          },
          hash: "img_three_c9502ebbd9",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 15.82,
          url: "/uploads/img_three_c9502ebbd9.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:13.909Z",
          updated_at: "2023-11-12T17:26:13.961Z",
        },
        media: {
          id: 86,
          name: "services_icon03.svg",
          alternativeText: "",
          caption: "",
          width: 43,
          height: 39,
          formats: null,
          hash: "services_icon03_84899c8eff",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 4.66,
          url: "/uploads/services_icon03_84899c8eff.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:09.618Z",
          updated_at: "2023-11-12T17:21:09.808Z",
        },
      },
      {
        id: 9,
        title: "HYBRID SOLAR PV SYSTEM",
        content:
          "The system operates on power generated using solar PV (photovoltaic) system.",
        button: null,
        link: "/services-details/Hybrid-Solar-PV-System/",
        slug: "services",
        published_at: "2023-11-14T03:28:08.643Z",
        created_at: "2023-11-14T03:28:05.980Z",
        updated_at: "2023-11-18T17:38:10.796Z",
        background_image: {
          id: 252,
          name: "img-four.jpg",
          alternativeText: "",
          caption: "",
          width: 276,
          height: 193,
          formats: {
            thumbnail: {
              name: "thumbnail_img-four.jpg",
              hash: "thumbnail_img_four_7d2bc10373",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 223,
              height: 156,
              size: 9.68,
              path: null,
              url: "/uploads/thumbnail_img_four_7d2bc10373.jpg",
            },
          },
          hash: "img_four_7d2bc10373",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 13.26,
          url: "/uploads/img_four_7d2bc10373.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:13.043Z",
          updated_at: "2023-11-12T17:26:13.372Z",
        },
        media: {
          id: 89,
          name: "services_icon04.svg",
          alternativeText: "",
          caption: "",
          width: 46,
          height: 46,
          formats: null,
          hash: "services_icon04_2e287671d2",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 5.33,
          url: "/uploads/services_icon04_2e287671d2.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:10.579Z",
          updated_at: "2023-11-12T17:21:10.653Z",
        },
      },
      {
        id: 10,
        title: "SOLAR WATER HEATER SYSTEM",
        content:
          "Investigationes demonstraverunt lectore legere me lius quod ii legunt saepius.",
        button: null,
        link: "/services-details/Solar-Water-Heater-System/",
        slug: "services",
        published_at: "2023-11-14T03:30:49.632Z",
        created_at: "2023-11-14T03:30:46.505Z",
        updated_at: "2023-11-18T17:38:39.986Z",
        background_image: {
          id: 249,
          name: "img-five.jpg",
          alternativeText: "",
          caption: "",
          width: 276,
          height: 193,
          formats: {
            thumbnail: {
              name: "thumbnail_img-five.jpg",
              hash: "thumbnail_img_five_f8165ecc4b",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 223,
              height: 156,
              size: 8.07,
              path: null,
              url: "/uploads/thumbnail_img_five_f8165ecc4b.jpg",
            },
          },
          hash: "img_five_f8165ecc4b",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 10.95,
          url: "/uploads/img_five_f8165ecc4b.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:12.211Z",
          updated_at: "2023-11-12T17:26:12.290Z",
        },
        media: {
          id: 90,
          name: "services_icon05.svg",
          alternativeText: "",
          caption: "",
          width: 42,
          height: 40,
          formats: null,
          hash: "services_icon05_e93c509fed",
          ext: ".svg",
          mime: "image/svg+xml",
          size: 7.45,
          url: "/uploads/services_icon05_e93c509fed.svg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:11.016Z",
          updated_at: "2023-11-12T17:21:11.204Z",
        },
      },
    ],
  },
  {
    id: 3,
    title: "Latest Projects",
    slug: "main-board-3",
    subtitle: "Explore Our Latest Projects",
    button_title: "View All Projects",
    button_link: "/project",
    published_at: "2023-11-14T05:25:09.633Z",
    created_at: "2023-11-14T05:25:07.057Z",
    updated_at: "2023-11-24T22:38:03.973Z",
    items: [],
    background_image: "/assets/img/bg/project_bg.jpg",
    projects: [
      {
        id: 2,
        title: "SOLAR WATER PUMPING SYSTEM",
        content:
          "This is a 5 kW solar water pumping system installed by SSES on 24th April, 2020. Mr. Sardar Akhtar Mengal (Member of National Assembly, Pakistan) sponsored...",
        subtitle: "5 kW Kangoori, Shah Noorani",
        link: "/project-details",
        shown_on_footer: null,
        type: null,
        parent: "main-board-3",
        slug: "5-k-w-kangoori-shah-noorani",
        published_at: "2023-11-24T22:36:59.383Z",
        created_at: "2023-11-24T22:34:34.803Z",
        updated_at: "2023-11-24T22:36:59.418Z",
        media: {
          id: 213,
          name: "single-project_1.jpg",
          alternativeText: "",
          caption: "",
          width: 1000,
          height: 408,
          hash: "single_project_1_6bdacf5cce",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 81.21,
          url: "/assets/img/project1/single-project_1.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:25:46.026Z",
          updated_at: "2023-11-12T17:25:46.215Z",
        },
      },
    ],
  },
  {
    id: 4,
    title: "Professional Team Member",
    slug: "team",
    subtitle: "Professional Team",
    button_title: null,
    button_link: null,
    published_at: "2023-11-24T23:52:55.461Z",
    created_at: "2023-11-24T23:52:53.313Z",
    updated_at: "2023-11-25T00:08:05.222Z",
    background_image: null,
    items: [],
    projects: [],
    team: [
      {
        id: 1,
        title: "Hassan Jafri",
        subtitle: "CEO/ Managing Director",
        social_link_1: "https://www.facebook.com/hassan.jafri.902/",
        social_link_2: "https://www.linkedin.com/in/hassan-jafri-7a6b171ba/",
        social_link_3:
          "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw",
        published_at: "2023-11-20T00:44:30.241Z",
        created_at: "2023-11-20T00:44:27.241Z",
        updated_at: "2023-11-25T00:38:10.800Z",
        media: {
          id: 281,
          name: "team-member1.jpg",
          alternativeText: "",
          caption: "",
          width: 264,
          height: 261,
          hash: "team_member1_38ae96159c",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 10.29,
          url: "/assets/img/team/team-member1.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:51.428Z",
          updated_at: "2023-11-12T17:26:51.556Z",
        },
      },
      {
        id: 2,
        title: "Abdul Hameed Mengal",
        subtitle: "CEO",
        social_link_1: "https://www.facebook.com/engr.mengal/",
        social_link_2: null,
        social_link_3:
          "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw/",
        published_at: "2023-11-20T00:45:58.300Z",
        created_at: "2023-11-20T00:45:55.398Z",
        updated_at: "2023-11-25T00:39:19.394Z",
        media: {
          id: 283,
          name: "team-member2.jpg",
          alternativeText: "",
          caption: "",
          width: 264,
          height: 261,
          formats: {
            thumbnail: {
              name: "thumbnail_team-member2.jpg",
              hash: "thumbnail_team_member2_09aa77a67c",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 158,
              height: 156,
              size: 6.38,
              path: null,
              url: "/uploads/thumbnail_team_member2_09aa77a67c.jpg",
            },
          },
          hash: "team_member2_09aa77a67c",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 12.35,
          url: "/uploads/team_member2_09aa77a67c.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:51.928Z",
          updated_at: "2023-11-12T17:26:52.030Z",
        },
      },
      {
        id: 3,
        title: "Muhammad Usama Nasir",
        subtitle: "Managing Director",
        social_link_1: "https://www.facebook.com/M.UsamaNasir/",
        social_link_2: "https://www.linkedin.com/in/mohammad-usama-518555a6/",
        social_link_3:
          "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw/",
        published_at: "2023-11-20T00:46:54.000Z",
        created_at: "2023-11-20T00:46:51.862Z",
        updated_at: "2023-11-25T00:39:51.879Z",
        media: {
          id: 285,
          name: "team-member3.jpg",
          alternativeText: "",
          caption: "",
          width: 264,
          height: 261,
          formats: {
            thumbnail: {
              name: "thumbnail_team-member3.jpg",
              hash: "thumbnail_team_member3_71e05482de",
              ext: ".jpg",
              mime: "image/jpeg",
              width: 158,
              height: 156,
              size: 5.11,
              path: null,
              url: "/uploads/thumbnail_team_member3_71e05482de.jpg",
            },
          },
          hash: "team_member3_71e05482de",
          ext: ".jpg",
          mime: "image/jpeg",
          size: 10.13,
          url: "/uploads/team_member3_71e05482de.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:26:52.333Z",
          updated_at: "2023-11-12T17:26:52.409Z",
        },
      },
    ],
    testimonials: [],
  },
  {
    id: 5,
    title: "Some of Our Respected Happy Clients Says",
    slug: "testimonials",
    subtitle: "Our Testimonial",
    button_title: null,
    button_link: null,
    published_at: "2023-11-25T20:43:59.782Z",
    created_at: "2023-11-25T20:43:57.358Z",
    updated_at: "2023-11-25T20:48:19.361Z",
    background_image: null,
    media: {
      id: 238,
      name: "project-06.jpg",
      alternativeText: "",
      caption: "",
      width: 466,
      height: 466,
      hash: "project_06_400ef127cf",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 62.96,
      url: "/assets/img/project1/project-06.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:55.886Z",
      updated_at: "2023-11-12T17:25:55.958Z",
    },
    items: [],
    projects: [],
    team: [],
    testimonials: [
      {
        id: 4,
        client_name: "Owais Zaki",
        designation: "(Area Manager Ideas By Gul Ahmed)",
        message:
          "I had installed the solar power generation system at my home \n                        through Sustainable Solar Energy Solutions & have been using\n                         it since July 2019. Alhamdulillah very satisfied with the work\n                          & the product. Excellent customer service, the team is very supportive\n                           & resolves any kind of issues immediately. <br /> P.S. The society i \n                           am living in has no K.E. connection yet. Solar power is the only source of\n                            electricity since I am against the Kunda system.",
        published_at: "2023-11-25T20:41:59.867Z",
        created_at: "2023-11-25T20:41:57.497Z",
        updated_at: "2023-11-25T20:41:59.897Z",
        avatar: null,
      },
      {
        id: 1,
        client_name: "Mr. Azhar Abbas",
        designation: "Head of Facilities Management, Habib University",
        message:
          "This is a young startup and with lot of promise and passion.\n                         Young graduates of alternate energy  have all relevant skills,\n                           techniques  and knowledge of this new emerging discipline. \n                           I recommend fully to their success,  as have seen on my project",
        published_at: "2023-11-25T20:36:00.099Z",
        created_at: "2023-11-25T20:35:57.532Z",
        updated_at: "2023-11-25T20:39:07.835Z",
        avatar: null,
      },
      {
        id: 2,
        client_name: "Yousuf Khan",
        designation: "General Manager (Energy and Engineering)Matiari Group.",
        message:
          "This team of young engineers has impressed me.\n                         In a small span of time they have achieved landmark success. \n                          They are energetic, intelligent, hard working,articulate and \n                          because of this they fix difficult targets and endeavour challenging projects\n                           for themselves, they then work diligently to achieve results\n                            and usually succeed. Their creative and result oriented approach is applaudable. \n                             I am glad to wish these young professionals pronounced success in their carrier.",
        published_at: "2023-11-25T20:39:54.088Z",
        created_at: "2023-11-25T20:39:51.630Z",
        updated_at: "2023-11-25T20:39:54.122Z",
        avatar: null,
      },
      {
        id: 3,
        client_name: "Mr. Imran Qayyum",
        designation: "Owner of Alpha Petroleum Services ( PSO Outlet )",
        message:
          "Sustainable Solar Energy Solution is a wonderful setup with young\n                         and qualified engineers who are experts in their field. I am fully satisfied \n                         with their services.",
        published_at: "2023-11-25T20:41:13.222Z",
        created_at: "2023-11-25T20:41:10.715Z",
        updated_at: "2023-11-25T20:41:13.273Z",
        avatar: {
          id: 131,
          name: "testi_avatar01.png",
          alternativeText: "",
          caption: "",
          width: 80,
          height: 80,
          formats: null,
          hash: "testi_avatar01_17d7b3f77c",
          ext: ".png",
          mime: "image/png",
          size: 5.3,
          url: "/assets/img/images/testi_avatar01.png",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          created_at: "2023-11-12T17:21:38.463Z",
          updated_at: "2023-11-12T17:21:38.532Z",
        },
      },
    ],
  },
];

export const aboutSection = {};
export const aboutSectionHome = {
  id: 1,
  title: "We’re Committed to Solar energy Excellence",
  subtitle: "About Our Company",
  content:
    "We are representing world's best and most renowned brands with a highly professional and knowledgeable team, one of the key element of our business is establishing long-lasting relationship with our clients.\n",
  button_title: "Learn More",
  button_link: "/about",
  list_content:
    "Market Partners have worked us.\nProfessional and experienced human resources.\nProvide the best solar services.",
  published_at: "2023-11-26T02:32:44.794Z",
  created_at: "2023-11-26T02:32:42.842Z",
  updated_at: "2023-11-26T03:18:52.364Z",
  items: [
    {
      id: 4,
      title: "We have years of experiences",
      content: null,
      link: null,
      slug: "about-section",
      button_title: null,
      button_link: null,
      published_at: "2023-11-14T03:02:09.948Z",
      created_at: "2023-11-14T03:02:04.421Z",
      updated_at: "2023-11-14T03:02:10.025Z",
      background_image: {
        id: 101,
        name: "about-woman.png",
        alternativeText: "",
        caption: "",
        width: 334,
        height: 543,
        formats: {
          thumbnail: {
            name: "thumbnail_about-woman.png",
            hash: "thumbnail_about_woman_aa155955e8",
            ext: ".png",
            mime: "image/png",
            width: 96,
            height: 156,
            size: 39.75,
            path: null,
            url: "/uploads/thumbnail_about_woman_aa155955e8.png",
          },
          small: {
            name: "small_about-woman.png",
            hash: "small_about_woman_aa155955e8",
            ext: ".png",
            mime: "image/png",
            width: 308,
            height: 500,
            size: 363.35,
            path: null,
            url: "/uploads/small_about_woman_aa155955e8.png",
          },
        },
        hash: "about_woman_aa155955e8",
        ext: ".png",
        mime: "image/png",
        size: 298.68,
        url: "/uploads/about_woman_aa155955e8.png",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:21:15.223Z",
        updated_at: "2023-11-12T17:21:15.298Z",
      },
      media: {
        id: 98,
        name: "about_icon01.svg",
        alternativeText: "",
        caption: "",
        width: 28,
        height: 32,
        formats: null,
        hash: "about_icon01_6b9514fa6b",
        ext: ".svg",
        mime: "image/svg+xml",
        size: 3.68,
        url: "/uploads/about_icon01_6b9514fa6b.svg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:21:14.238Z",
        updated_at: "2023-11-12T17:21:14.345Z",
      },
    },
    {
      id: 5,
      title: "We use professional and experienced person",
      content: null,
      link: null,
      slug: "about-section",
      button_title: null,
      button_link: null,
      published_at: "2023-11-14T03:04:00.977Z",
      created_at: "2023-11-14T03:03:58.592Z",
      updated_at: "2023-11-14T03:04:01.049Z",
      background_image: {
        id: 82,
        name: "mission-img3.jpg",
        alternativeText: "",
        caption: "",
        width: 213,
        height: 386,
        formats: {
          thumbnail: {
            name: "thumbnail_mission-img3.jpg",
            hash: "thumbnail_mission_img3_0b31835b74",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 86,
            height: 156,
            size: 2.58,
            path: null,
            url: "/uploads/thumbnail_mission_img3_0b31835b74.jpg",
          },
        },
        hash: "mission_img3_0b31835b74",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 8.04,
        url: "/uploads/mission_img3_0b31835b74.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:21:07.701Z",
        updated_at: "2023-11-12T17:21:07.765Z",
      },
      media: {
        id: 100,
        name: "about_icon02.svg",
        alternativeText: "",
        caption: "",
        width: 39,
        height: 33,
        formats: null,
        hash: "about_icon02_4fd770749e",
        ext: ".svg",
        mime: "image/svg+xml",
        size: 3.32,
        url: "/uploads/about_icon02_4fd770749e.svg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:21:14.776Z",
        updated_at: "2023-11-12T17:21:14.825Z",
      },
    },
  ],
};

export const faqPageContent = {
  id: 1,
  title: "Have Any Questions Answer?",
  subtitle: "Our Faqs",
  banner: {
    id: 3,
    title: "FAQ",
    content: null,
    button: null,
    slug: "faq",
    breadcrumb: "FAQ",
    published_at: "2023-11-19T16:37:44.900Z",
    created_at: "2023-11-19T16:37:42.138Z",
    updated_at: "2023-11-19T16:37:44.977Z",
    background_image: {
      id: 145,
      name: "breadcrumb_shape.png",
      alternativeText: "",
      caption: "",
      width: 877,
      height: 242,
      formats: {
        thumbnail: {
          name: "thumbnail_breadcrumb_shape.png",
          hash: "thumbnail_breadcrumb_shape_385428e1e1",
          ext: ".png",
          mime: "image/png",
          width: 245,
          height: 68,
          size: 4.23,
          path: null,
          url: "/uploads/thumbnail_breadcrumb_shape_385428e1e1.png",
        },
        medium: {
          name: "medium_breadcrumb_shape.png",
          hash: "medium_breadcrumb_shape_385428e1e1",
          ext: ".png",
          mime: "image/png",
          width: 750,
          height: 207,
          size: 13.18,
          path: null,
          url: "/uploads/medium_breadcrumb_shape_385428e1e1.png",
        },
        small: {
          name: "small_breadcrumb_shape.png",
          hash: "small_breadcrumb_shape_385428e1e1",
          ext: ".png",
          mime: "image/png",
          width: 500,
          height: 138,
          size: 8.88,
          path: null,
          url: "/uploads/small_breadcrumb_shape_385428e1e1.png",
        },
      },
      hash: "breadcrumb_shape_385428e1e1",
      ext: ".png",
      mime: "image/png",
      size: 4.75,
      url: "/uploads/breadcrumb_shape_385428e1e1.png",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:42.347Z",
      updated_at: "2023-11-12T17:21:42.414Z",
    },
    background_image_2: {
      id: 18,
      name: "breadcrumb_bg.jpg",
      alternativeText: "",
      caption: "",
      width: 1920,
      height: 300,
      formats: {
        thumbnail: {
          name: "thumbnail_breadcrumb_bg.jpg",
          hash: "thumbnail_breadcrumb_bg_c56c0d99ac",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 245,
          height: 38,
          size: 1.93,
          path: null,
          url: "/uploads/thumbnail_breadcrumb_bg_c56c0d99ac.jpg",
        },
        large: {
          name: "large_breadcrumb_bg.jpg",
          hash: "large_breadcrumb_bg_c56c0d99ac",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 1000,
          height: 156,
          size: 14.34,
          path: null,
          url: "/uploads/large_breadcrumb_bg_c56c0d99ac.jpg",
        },
        medium: {
          name: "medium_breadcrumb_bg.jpg",
          hash: "medium_breadcrumb_bg_c56c0d99ac",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 750,
          height: 117,
          size: 9.02,
          path: null,
          url: "/uploads/medium_breadcrumb_bg_c56c0d99ac.jpg",
        },
        small: {
          name: "small_breadcrumb_bg.jpg",
          hash: "small_breadcrumb_bg_c56c0d99ac",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 500,
          height: 78,
          size: 4.8,
          path: null,
          url: "/uploads/small_breadcrumb_bg_c56c0d99ac.jpg",
        },
      },
      hash: "breadcrumb_bg_c56c0d99ac",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 38.72,
      url: "/uploads/breadcrumb_bg_c56c0d99ac.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:19:31.507Z",
      updated_at: "2023-11-12T17:19:31.641Z",
    },
  },
  published_at: "2023-11-19T16:38:34.979Z",
  created_at: "2023-11-19T16:38:32.554Z",
  updated_at: "2023-11-19T16:53:15.579Z",
  media_1: {
    id: 111,
    name: "faq_img01.jpg",
    alternativeText: "",
    caption: "",
    width: 332,
    height: 628,
    formats: {
      thumbnail: {
        name: "thumbnail_faq_img01.jpg",
        hash: "thumbnail_faq_img01_1cefa86b39",
        ext: ".jpg",
        mime: "image/jpeg",
        width: 82,
        height: 156,
        size: 3.7,
        path: null,
        url: "/uploads/thumbnail_faq_img01_1cefa86b39.jpg",
      },
      small: {
        name: "small_faq_img01.jpg",
        hash: "small_faq_img01_1cefa86b39",
        ext: ".jpg",
        mime: "image/jpeg",
        width: 264,
        height: 500,
        size: 19.51,
        path: null,
        url: "/uploads/small_faq_img01_1cefa86b39.jpg",
      },
    },
    hash: "faq_img01_1cefa86b39",
    ext: ".jpg",
    mime: "image/jpeg",
    size: 27.01,
    url: "/uploads/faq_img01_1cefa86b39.jpg",
    previewUrl: null,
    provider: "local",
    provider_metadata: null,
    created_at: "2023-11-12T17:21:30.650Z",
    updated_at: "2023-11-12T17:21:30.714Z",
  },
  media_2: {
    id: 113,
    name: "faq_img02.jpg",
    alternativeText: "",
    caption: "",
    width: 332,
    height: 628,
    formats: {
      thumbnail: {
        name: "thumbnail_faq_img02.jpg",
        hash: "thumbnail_faq_img02_6e31cc082a",
        ext: ".jpg",
        mime: "image/jpeg",
        width: 82,
        height: 156,
        size: 4.01,
        path: null,
        url: "/uploads/thumbnail_faq_img02_6e31cc082a.jpg",
      },
      small: {
        name: "small_faq_img02.jpg",
        hash: "small_faq_img02_6e31cc082a",
        ext: ".jpg",
        mime: "image/jpeg",
        width: 264,
        height: 500,
        size: 21.93,
        path: null,
        url: "/uploads/small_faq_img02_6e31cc082a.jpg",
      },
    },
    hash: "faq_img02_6e31cc082a",
    ext: ".jpg",
    mime: "image/jpeg",
    size: 30.65,
    url: "/uploads/faq_img02_6e31cc082a.jpg",
    previewUrl: null,
    provider: "local",
    provider_metadata: null,
    created_at: "2023-11-12T17:21:31.692Z",
    updated_at: "2023-11-12T17:21:31.835Z",
  },
  items: [
    {
      id: 1,
      title: "What components does a solar powered system have?",
      content:
        "A solar powered energy system consists of solar panels, inverter, mounting structure for solar panels, electrical wiring, breakers and sometime batteries.",
      expanded: true,
      published_at: "2023-11-19T14:11:56.134Z",
      created_at: "2023-11-19T14:10:52.990Z",
      updated_at: "2023-11-19T23:59:32.771Z",
    },
    {
      id: 2,
      title: "How does a solar powered system work?",
      content:
        "Photovoltaic (PV) cells in solar panels convert sunlight into direct current (DC). Inverters then convert the DC electricity into the alternating current (AC) which is then transferred to the main electrical distribution panel (DB) for use. In off-grid and hybrid systems, batteries can be used for storing the initial DC electricity coming from the solar panels through a charge controller.",
      expanded: false,
      published_at: "2023-11-20T00:02:15.224Z",
      created_at: "2023-11-20T00:02:13.136Z",
      updated_at: "2023-11-20T00:02:15.267Z",
    },
    {
      id: 3,
      title: "How does net-metering work?",
      content:
        "Net-Metering concept is a process that allows customers to produce their own solar power and share their surplus electricity with the national grid. The monthly bill is then netted off in proportional to the amount of energy sold to the distribution company. The net metering procedure is used globally to promote the use of distributed generation.",
      expanded: false,
      published_at: "2023-12-17T20:09:19.309Z",
      created_at: "2023-12-17T20:09:14.908Z",
      updated_at: "2023-12-17T23:15:32.038Z",
    },
    {
      id: 5,
      title: "How much space would I need to install my solar powered system?",
      content:
        "Space requirements range from 100 to 130 square feet per kW of solar PV installed, depending the tilt angle of the solar PV modules and facing towards the path that sun follows in that region.",
      expanded: false,
      published_at: "2023-12-17T23:21:22.271Z",
      created_at: "2023-12-17T23:21:20.170Z",
      updated_at: "2023-12-17T23:21:22.295Z",
    },
    {
      id: 6,
      title: "What if my system produces more energy than I require?",
      content:
        "The excess electricity would either be sold back to the grid using the net metering or will be stored in the form of batteries and used later by the same load center.",
      expanded: false,
      published_at: "2023-12-17T23:21:54.322Z",
      created_at: "2023-12-17T23:21:52.423Z",
      updated_at: "2023-12-17T23:21:54.340Z",
    },
    {
      id: 7,
      title:
        "Will the weight of the solar PV system be of any concern for my roof?",
      content:
        "Concrete roofs have no problems at all in handling the distributed load nature of solar PV panels and its frames, however T-slabs & truss based roofs have to be analyzed first before they are used for installation.",
      expanded: false,
      published_at: "2023-12-17T23:22:44.646Z",
      created_at: "2023-12-17T23:22:42.789Z",
      updated_at: "2023-12-17T23:22:44.667Z",
    },
    {
      id: 4,
      title: "What of its maintenance?",
      content:
        "The only kind of maintenance a solar powered energy system requires is the cleaning of solar panel itself and nothing else. The frequency of cleaning can be weekly or bi-monthly according to the site situation.",
      expanded: false,
      published_at: "2023-12-17T23:20:47.052Z",
      created_at: "2023-12-17T23:20:45.054Z",
      updated_at: "2023-12-17T23:20:47.072Z",
    },
    {
      id: 9,
      title: "Does SSES provide O&M services?",
      content: "Yes, we do.",
      expanded: false,
      published_at: "2023-12-17T23:23:31.751Z",
      created_at: "2023-12-17T23:23:29.851Z",
      updated_at: "2023-12-17T23:23:31.773Z",
    },
    {
      id: 10,
      title: "<b>Sustainable Solar Energy Solutions - SSES</b>",
      content: null,
      expanded: false,
      published_at: "2023-12-17T23:25:44.358Z",
      created_at: "2023-12-17T23:25:42.084Z",
      updated_at: "2023-12-17T23:25:44.381Z",
    },
    {
      id: 12,
      title: "What is the point of origin of SSES’s products?",
      content:
        "SSES sources its components from various countries. Some of these countries include Germany, Austria, Italy, United States, China and Pakistan. SSES focuses its efforts on designing the most optimum technical and commercial solution on a case to case basis.",
      expanded: false,
      published_at: "2023-12-17T23:28:10.369Z",
      created_at: "2023-12-17T23:28:08.533Z",
      updated_at: "2023-12-17T23:28:10.386Z",
    },
    {
      id: 13,
      title:
        "How to check if the components offered are off the best quality or not?",
      content:
        "There is nothing hidden during these times of information available at hand. Nowadays market is full of deceit. We give our costumer the virtual choices they can select from according to their requirement and need after they choose and the goods are delivered, they can scan the QR codes of those equipment to cross check what they had chosen earlier.",
      expanded: false,
      published_at: "2023-12-17T23:28:46.984Z",
      created_at: "2023-12-17T23:28:45.077Z",
      updated_at: "2023-12-17T23:28:47.003Z",
    },
    {
      id: 14,
      title:
        "What safety protocols are important to consider while putting up a solar PV system?",
      content:
        "The National Electric Code (NEC) is an electrical safety code and has a section dedicated to solar PV system electrical installations safety. The NEC drives several design and installation decisions. The National Fire Protection Association (NFPA) has dedicated sections on hazard identification and installation best practices for solar PV systems. California Fire Code (CalFire) is a set of rooftop solar installation safety best practices made by the state of California and used globally for installing solar PV modules to facilitate fire emergency services. International building Code (IBC) used for standard safety practices to evaluate roofs/structures before installing solar PV modules.",
      expanded: false,
      published_at: "2023-12-17T23:29:33.516Z",
      created_at: "2023-12-17T23:29:31.428Z",
      updated_at: "2023-12-17T23:29:33.532Z",
    },
    {
      id: 15,
      title: "How much would a solar powered system installed by SSES cost?",
      content:
        "SSES can provide the best information on what it will cost to go solar for your load. However, once customers begin to explore solar options, they can find vastly varying rates in the market for the same system, what differ are the genuine parts and equipment used by us and some local street vendors. Moreover it is important for costumers to know that the total up-front cost of solar is less relevant than the financing terms, return-on-investment, and cash flow calculation. Financial options such as solar leases and other innovative financing models can help you convert to solar for little or no money along with an efficient design that can also help bring the costs down.",
      expanded: false,
      published_at: "2023-12-17T23:30:33.944Z",
      created_at: "2023-12-17T23:30:31.720Z",
      updated_at: "2023-12-17T23:30:33.963Z",
    },
    {
      id: 8,
      title: "How long does a solar powered energy system last?",
      content:
        "Our systems are designed to have a useful life of 25 years or much more, according to the climate and atmosphere it has been used it.",
      expanded: false,
      published_at: "2023-12-17T23:23:03.929Z",
      created_at: "2023-12-17T23:23:01.897Z",
      updated_at: "2023-12-17T23:23:03.952Z",
    },
    {
      id: 11,
      title: "Why should we go with SSES?",
      content:
        "<p>SSES was started by the first ever Energy Engineers of Pakistan. We are here to elevate the standards of services in the solar field. SSES has successfully installed hundreds of solar projects with unbeatable price and services within Pakistan. We strive to live by the following codes of ethic.</p><p>• Use of correct design principles.</p><p>• Always use original and quality products. </p><p>• Eliminate incorrect installation practices. </p><p>• Safety of client and labor always comes first. </p>",
      expanded: false,
      published_at: "2023-12-17T23:27:29.791Z",
      created_at: "2023-12-17T23:27:27.582Z",
      updated_at: "2023-12-17T23:27:29.810Z",
    },
  ],
};

export const team = [{}];

export const services = [
  {
    id: 1,
    title: "Solar Water Pumping System",
    content:
      "The system operates on power generated using solar PV (photovoltaic) system. The photovoltaic array converts the solar energy into electricity, which is used for running the motor pump set. The pumping system draws water from the open well, bore well, stream, pond, canal etc.\n\nSolar water pumping systems can be a practical and affordable solution used to provide reliable and cost effective water supplies where there is no grid power or where power supply is unreliable. The advantages of these systems include:\n\nSolar pumps operate anywhere the sun shines.\nSystem productivity increases in summer when water requirement is usually greater.\nPowered by clean, renewable energy.\nVirtually free to operate, compared to the cost of diesel-powered generators and grid electricity which is constantly increasing.\nEasily relocated to meet seasonal or variable location needs.\nBecause solar systems only operate during daylight hours the water pumped out is typically stored in a storage tank for use 24 hours per day, to ensure constant availability of water. The tank capacity should be designed to allow for rainy or cloudy days (no sun days) when pumping will be limited. The size and dimensions of the storage tank is determined based on the required number of day’s storage. If large storage tanks are impractical, back up batteries or a generator can also be incorporated in the design to allow for prolonged periods of no sun days that will eventually empty the water storage tank.\n\nPossible applications include:\n\nLivestock – cattle watering and fish farming.\nAgriculture – irrigation or crop watering.\nRecreational – swimming pool circulation pumps; spa.\nResidential – water supply for drinking or pressure boosting.\nIndustrial – water supply for businesses.\nPumping can be by submersible pumps, commonly used for deeper wells, where surface pumps cannot be used because the water level is too deep below ground level (below approximately 6 meters depth). These borehole pumps are specially designed to have a small outside diameter so they can be suspended below the water level in the well and connected to an output pipe that extends up to the surface. The right pump for each application will depend on the requir ed pumping rates and pumping height and distance.\n\nAlternatively, surface pumps are used to move water from sources such as shallow wells, ponds, streams, and tanks, where the pump itself can be located no more than 6 meters above the water level. There are many types of pump available; the choice will depend on how much water per day needs to be moved and the height and distance to the delivery point (such as the storage tank). Pump efficiency and reliability can be improved if suction lift can be minimized to just a few meters.\n\nGetting the most benefit from solar water pumping systems requires research and design before the first PV module and a pump is purchased and installed. Each component must be carefully matched, and proper planning is essential – so the final system will be efficient and reliable and can function for many years to come. Groundwater Engineering’s team has extensive experience in solar PV and solar water pumping systems and we can offer a complete design and installation service to meet client needs.",
    slug: "solar-water-pumping-system",
    excerpt:
      "The system operates on power generated using solar PV (photovoltaic) system.",
    button_text: "Read More",
    button_link: "/services-details",
    service_identifier: "Solar Water Pumping System",
    published_at: "2023-11-29T22:18:31.149Z",
    created_at: "2023-11-29T22:18:27.611Z",
    updated_at: "2023-12-02T10:53:40.656Z",
    media: {
      id: 215,
      name: "single-project_4.jpg",
      alternativeText: "",
      caption: "",
      width: 1000,
      height: 408,
      hash: "single_project_4_a2171df65c",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 64.94,
      url: "/assets/img/project1/single-project_4.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:47.211Z",
      updated_at: "2023-11-12T17:25:47.312Z",
    },
    background_image: {
      id: 253,
      name: "img-one.jpg",
      alternativeText: "",
      caption: "",
      width: 276,
      height: 193,
      formats: {
        thumbnail: {
          name: "thumbnail_img-one.jpg",
          hash: "thumbnail_img_one_17b12fa848",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 223,
          height: 156,
          size: 13.1,
          path: null,
          url: "/uploads/thumbnail_img_one_17b12fa848.jpg",
        },
      },
      hash: "img_one_17b12fa848",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 19.92,
      url: "/uploads/img_one_17b12fa848.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:26:13.629Z",
      updated_at: "2023-11-12T17:26:13.685Z",
    },
    icon_image: {
      id: 87,
      name: "services_icon01.svg",
      alternativeText: "",
      caption: "",
      width: 39,
      height: 39,
      formats: null,
      hash: "services_icon01_766ac6a7ca",
      ext: ".svg",
      mime: "image/svg+xml",
      size: 1.77,
      url: "/uploads/services_icon01_766ac6a7ca.svg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:09.995Z",
      updated_at: "2023-11-12T17:21:10.089Z",
    },
  },
  {
    id: 2,
    title: "ON-GRID SOLAR SYSTEM",
    content:
      "On-grid or grid-tie solar systems are by far the most common and widely used by homes and businesses. These systems do not need batteries and use common solar inverters and are connected to the public electricity grid. Any excess solar power that you generate is exported to the electricity grid and you usually get paid a feed-in-tariff (FiT) or credits for the energy you export.\n\nUnlike hybrid systems, on-grid solar systems are not able to function or generate electricity during a blackout due to safety reasons.\nSince blackouts usually occur when the electricity grid is damaged; If the solar inverter was still feeding electricity into a damaged grid it would risk the safety of the people repairing the fault/s in the network.\nMost hybrid solar systems with battery storage are able to automatically isolate from the grid (known as islanding) and continue to supply some power during a blackout.",
    slug: "on-grid-solar-system",
    excerpt:
      "On-grid or grid-tie solar systems are by far the most common & widely used.",
    button_text: "Read More",
    button_link: "/services-details",
    service_identifier: "ON-GRID SOLAR SYSTEM",
    published_at: "2023-11-30T00:46:18.357Z",
    created_at: "2023-11-30T00:46:14.183Z",
    updated_at: "2023-12-02T10:53:58.011Z",
    media: {
      id: 207,
      name: "service-slide-2.jpg",
      alternativeText: "",
      caption: "",
      width: 792,
      height: 325,
      hash: "service_slide_2_93db2006be",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 55.9,
      url: "/assets/img/project1/service-slide-2.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:42.633Z",
      updated_at: "2023-11-12T17:25:42.899Z",
    },
    background_image: {
      id: 255,
      name: "img-two.jpg",
      alternativeText: "",
      caption: "",
      width: 276,
      height: 193,
      formats: {
        thumbnail: {
          name: "thumbnail_img-two.jpg",
          hash: "thumbnail_img_two_09851b62f5",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 223,
          height: 156,
          size: 10.52,
          path: null,
          url: "/uploads/thumbnail_img_two_09851b62f5.jpg",
        },
      },
      hash: "img_two_09851b62f5",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 15.3,
      url: "/uploads/img_two_09851b62f5.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:26:14.684Z",
      updated_at: "2023-11-12T17:26:14.792Z",
    },
    icon_image: {
      id: 85,
      name: "services_icon02.svg",
      alternativeText: "",
      caption: "",
      width: 62,
      height: 33,
      formats: null,
      hash: "services_icon02_72d8b4b668",
      ext: ".svg",
      mime: "image/svg+xml",
      size: 5.2,
      url: "/uploads/services_icon02_72d8b4b668.svg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:09.250Z",
      updated_at: "2023-11-12T17:21:09.367Z",
    },
  },
  {
    id: 3,
    title: "OFF-GRID SOLAR SYSTEM",
    content:
      "An off-grid system is not connected to the electricity grid and therefore requires battery storage. An off-grid solar system must be designed appropriately so that it will generate enough power throughout the year and have enough battery capacity to meet the home’s requirements, even in the depths of winter when there is less sunlight.\n\nThe high cost of batteries and inverters means off-grid systems are much more expensive than on-grid systems and so are usually only needed in more remote areas that are far from the electricity grid.\nHowever battery costs a re reducing rapidly, so there is now a growing market for off-grid solar battery systems even in cities and towns.",
    slug: "off-grid-solar-system",
    excerpt: "An off-grid system is not connected to the electricity grid.",
    button_text: "Read More",
    button_link: "/services-details",
    service_identifier: "OFF-GRID SOLAR SYSTEM",
    published_at: "2023-11-30T00:53:15.898Z",
    created_at: "2023-11-30T00:53:04.285Z",
    updated_at: "2023-12-02T10:54:11.332Z",
    media: {
      id: 208,
      name: "service-slide-3.jpg",
      alternativeText: "",
      caption: "",
      width: 792,
      height: 325,
      hash: "service_slide_3_46432aa0b4",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 71.44,
      url: "/assets/img/project1/service-slide-3.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:44.120Z",
      updated_at: "2023-11-12T17:25:44.243Z",
    },
    background_image: {
      id: 254,
      name: "img-three.jpg",
      alternativeText: "",
      caption: "",
      width: 276,
      height: 193,
      formats: {
        thumbnail: {
          name: "thumbnail_img-three.jpg",
          hash: "thumbnail_img_three_c9502ebbd9",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 223,
          height: 156,
          size: 11.42,
          path: null,
          url: "/uploads/thumbnail_img_three_c9502ebbd9.jpg",
        },
      },
      hash: "img_three_c9502ebbd9",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 15.82,
      url: "/uploads/img_three_c9502ebbd9.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:26:13.909Z",
      updated_at: "2023-11-12T17:26:13.961Z",
    },
    icon_image: {
      id: 86,
      name: "services_icon03.svg",
      alternativeText: "",
      caption: "",
      width: 43,
      height: 39,
      formats: null,
      hash: "services_icon03_84899c8eff",
      ext: ".svg",
      mime: "image/svg+xml",
      size: 4.66,
      url: "/uploads/services_icon03_84899c8eff.svg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:09.618Z",
      updated_at: "2023-11-12T17:21:09.808Z",
    },
  },
  {
    id: 4,
    title: "HYBRID SOLAR PV SYSTEM",
    content:
      "Modern hybrid systems combine solar and battery storage in one and are now available in many different forms and configurations.\n\nDue to the decreasing cost of battery storage, systems that are already connected to the electricity grid can start taking advantage of battery storage as well.\nThis means being able to store solar energy that is generated during the day and using it at night.\nWhen the stored energy is depleted, the grid is there as a back-up, allowing consumers to have the best of both worlds.\nHybrid systems are also able to charge the batteries using cheap off-peak electricity (usually after midnight to 6am).",
    slug: "hybrid-solar-pv-system",
    excerpt:
      "The system operates on power generated using solar PV (photovoltaic) system.",
    button_text: "Read More",
    button_link: "/services-details",
    service_identifier: "Hybrid Solar PV System",
    published_at: "2023-11-30T00:56:52.426Z",
    created_at: "2023-11-30T00:56:49.120Z",
    updated_at: "2023-12-02T10:56:35.529Z",
    media: {
      id: 209,
      name: "service-slide-4.jpg",
      alternativeText: "",
      caption: "",
      width: 792,
      height: 325,
      hash: "service_slide_4_4ba30758e0",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 60.67,
      url: "/assets/img/project1/service-slide-4.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:44.349Z",
      updated_at: "2023-11-12T17:25:44.472Z",
    },
    background_image: {
      id: 252,
      name: "img-four.jpg",
      alternativeText: "",
      caption: "",
      width: 276,
      height: 193,
      formats: {
        thumbnail: {
          name: "thumbnail_img-four.jpg",
          hash: "thumbnail_img_four_7d2bc10373",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 223,
          height: 156,
          size: 9.68,
          path: null,
          url: "/uploads/thumbnail_img_four_7d2bc10373.jpg",
        },
      },
      hash: "img_four_7d2bc10373",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 13.26,
      url: "/uploads/img_four_7d2bc10373.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:26:13.043Z",
      updated_at: "2023-11-12T17:26:13.372Z",
    },
    icon_image: {
      id: 89,
      name: "services_icon04.svg",
      alternativeText: "",
      caption: "",
      width: 46,
      height: 46,
      formats: null,
      hash: "services_icon04_2e287671d2",
      ext: ".svg",
      mime: "image/svg+xml",
      size: 5.33,
      url: "/uploads/services_icon04_2e287671d2.svg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:10.579Z",
      updated_at: "2023-11-12T17:21:10.653Z",
    },
  },
  {
    id: 5,
    title: "SOLAR WATER HEATER SYSTEM",
    content:
      "Solar water heating (SWH) is the conversion of sunlight into heat for water heating using a solar thermal collector. A variety of configurations are available at varying cost to provide solutions in different conditions.\n\nA sun-facing collector heats a working fluid that passes into a storage system for later use.\nSWH are active (pumped) and passive (convection/gravity-driven).\nThey use water only, or both water and a working fluid.\nThey operate independently or as hybrids with electric or gas heaters.",
    slug: "solar-water-heater-system",
    excerpt:
      "Investigationes demonstraverunt lectore legere me lius quod ii legunt saepius.",
    button_text: "Read More",
    button_link: "/services-details",
    service_identifier: "Metal Engineering",
    published_at: "2023-11-30T01:00:38.301Z",
    created_at: "2023-11-30T01:00:35.549Z",
    updated_at: "2023-12-02T10:56:54.741Z",
    media: {
      id: 209,
      name: "service-slide-4.jpg",
      alternativeText: "",
      caption: "",
      width: 792,
      height: 325,
      hash: "service_slide_4_4ba30758e0",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 60.67,
      url: "/assets/img/project1/service-slide-4.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:25:44.349Z",
      updated_at: "2023-11-12T17:25:44.472Z",
    },
    background_image: {
      id: 249,
      name: "img-five.jpg",
      alternativeText: "",
      caption: "",
      width: 276,
      height: 193,
      formats: {
        thumbnail: {
          name: "thumbnail_img-five.jpg",
          hash: "thumbnail_img_five_f8165ecc4b",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 223,
          height: 156,
          size: 8.07,
          path: null,
          url: "/uploads/thumbnail_img_five_f8165ecc4b.jpg",
        },
      },
      hash: "img_five_f8165ecc4b",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 10.95,
      url: "/uploads/img_five_f8165ecc4b.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:26:12.211Z",
      updated_at: "2023-11-12T17:26:12.290Z",
    },
    icon_image: {
      id: 90,
      name: "services_icon05.svg",
      alternativeText: "",
      caption: "",
      width: 42,
      height: 40,
      formats: null,
      hash: "services_icon05_e93c509fed",
      ext: ".svg",
      mime: "image/svg+xml",
      size: 7.45,
      url: "/uploads/services_icon05_e93c509fed.svg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:21:11.016Z",
      updated_at: "2023-11-12T17:21:11.204Z",
    },
  },
];

export const contactUs = {
  banner: {
    id: 1,
    title: "Best Solar Services and Consulting",
    content:
      "We are an EPC (Engineering, Procurement and Construction) company that provides cost effective and environment friendly solar energy solutions.",
    slug: "main",
    breadcrumb: null,
    button_title: "Discover More",
    button_link: "/project",
    published_at: "2023-11-14T02:13:09.641Z",
    created_at: "2023-11-14T02:13:04.076Z",
    updated_at: "2023-11-26T00:23:17.410Z",
    background_image: {
      id: 12,
      name: "img-three.jpg",
      alternativeText: "",
      caption: "",
      width: 1400,
      height: 788,
      formats: {
        thumbnail: {
          name: "thumbnail_img-three.jpg",
          hash: "thumbnail_img_three_b078a70059",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 245,
          height: 138,
          size: 11.71,
          path: null,
          url: "/uploads/thumbnail_img_three_b078a70059.jpg",
        },
        large: {
          name: "large_img-three.jpg",
          hash: "large_img_three_b078a70059",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 1000,
          height: 563,
          size: 162.96,
          path: null,
          url: "/uploads/large_img_three_b078a70059.jpg",
        },
        medium: {
          name: "medium_img-three.jpg",
          hash: "medium_img_three_b078a70059",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 750,
          height: 422,
          size: 95.78,
          path: null,
          url: "/uploads/medium_img_three_b078a70059.jpg",
        },
        small: {
          name: "small_img-three.jpg",
          hash: "small_img_three_b078a70059",
          ext: ".jpg",
          mime: "image/jpeg",
          width: 500,
          height: 281,
          size: 45.14,
          path: null,
          url: "/uploads/small_img_three_b078a70059.jpg",
        },
      },
      hash: "img_three_b078a70059",
      ext: ".jpg",
      mime: "image/jpeg",
      size: 301.39,
      url: "/uploads/img_three_b078a70059.jpg",
      previewUrl: null,
      provider: "local",
      provider_metadata: null,
      created_at: "2023-11-12T17:19:13.851Z",
      updated_at: "2023-11-12T17:19:13.888Z",
    },
    background_image_2: null,
  },
  boards: [
    {
      id: 1,
      title: null,
      slug: "main-board-1",
      subtitle: null,
      button_title: null,
      button_link: null,
      published_at: "2023-11-14T03:11:10.891Z",
      created_at: "2023-11-14T03:11:08.367Z",
      updated_at: "2023-11-18T21:10:59.237Z",
      background_image: null,
      media: null,
      items: [
        {
          id: 1,
          title: "Quality Materials",
          content: "You can expect superior quality solar modules.",
          link: null,
          slug: "main-board-1",
          button_title: "Read More",
          button_link: "/services-details",
          published_at: "2023-11-14T02:30:37.001Z",
          created_at: "2023-11-14T02:30:31.957Z",
          updated_at: "2023-11-26T02:29:11.034Z",
          background_image: null,
          media: {
            id: 72,
            name: "features_icon01.svg",
            alternativeText: "",
            caption: "",
            width: 39,
            height: 41,
            formats: null,
            hash: "features_icon01_21591fe95c",
            ext: ".svg",
            mime: "image/svg+xml",
            size: 14.74,
            url: "/uploads/features_icon01_21591fe95c.svg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:21:05.214Z",
            updated_at: "2023-11-12T17:21:05.300Z",
          },
        },
        {
          id: 2,
          title: "Expert Engineer",
          content:
            "Dedicated team of certified installers performing calculations, analysis and designs for your ease.",
          link: null,
          slug: "main-board-1",
          button_title: "Read More",
          button_link: "/services-details",
          published_at: "2023-11-14T02:42:19.525Z",
          created_at: "2023-11-14T02:41:51.294Z",
          updated_at: "2023-11-26T02:29:22.456Z",
          background_image: null,
          media: {
            id: 73,
            name: "features_icon02.svg",
            alternativeText: "",
            caption: "",
            width: 50,
            height: 39,
            formats: null,
            hash: "features_icon02_ea56f47253",
            ext: ".svg",
            mime: "image/svg+xml",
            size: 4.29,
            url: "/uploads/features_icon02_ea56f47253.svg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:21:05.426Z",
            updated_at: "2023-11-12T17:21:05.490Z",
          },
        },
        {
          id: 3,
          title: "Quality Maintenance",
          content:
            "Moreover, an impeccable after-sale service is our selling proposition.",
          link: null,
          slug: "main-board-1",
          button_title: "Read More",
          button_link: "/services-details",
          published_at: "2023-11-14T02:43:22.159Z",
          created_at: "2023-11-14T02:43:18.988Z",
          updated_at: "2023-11-26T02:29:32.568Z",
          background_image: null,
          media: {
            id: 74,
            name: "features_icon03.svg",
            alternativeText: "",
            caption: "",
            width: 38,
            height: 38,
            formats: null,
            hash: "features_icon03_a1ca7b6e98",
            ext: ".svg",
            mime: "image/svg+xml",
            size: 5.85,
            url: "/uploads/features_icon03_a1ca7b6e98.svg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:21:05.575Z",
            updated_at: "2023-11-12T17:21:05.623Z",
          },
        },
      ],
      projects: [],
      team: [],
      testimonials: [],
    },
    {
      id: 2,
      title: "What We Do",
      slug: "services",
      subtitle: "Our Services Areas",
      button_title: null,
      button_link: null,
      published_at: "2023-11-14T03:13:39.893Z",
      created_at: "2023-11-14T03:12:25.528Z",
      updated_at: "2023-11-18T21:11:37.953Z",
      background_image: null,
      media: null,
      items: [],
      projects: [],
      team: [],
      testimonials: [],
    },
    {
      id: 3,
      title: "Latest Projects",
      slug: "main-board-3",
      subtitle: "Explore Our Latest Projects",
      button_title: "View All Projects",
      button_link: "/project",
      published_at: "2023-11-14T05:25:09.633Z",
      created_at: "2023-11-14T05:25:07.057Z",
      updated_at: "2023-11-24T23:08:07.788Z",
      background_image: {
        id: 24,
        name: "project_bg.jpg",
        alternativeText: "",
        caption: "",
        width: 1920,
        height: 1329,
        formats: {
          thumbnail: {
            name: "thumbnail_project_bg.jpg",
            hash: "thumbnail_project_bg_578b15fc21",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 226,
            height: 156,
            size: 1.11,
            path: null,
            url: "/uploads/thumbnail_project_bg_578b15fc21.jpg",
          },
          large: {
            name: "large_project_bg.jpg",
            hash: "large_project_bg_578b15fc21",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 1000,
            height: 692,
            size: 27.63,
            path: null,
            url: "/uploads/large_project_bg_578b15fc21.jpg",
          },
          medium: {
            name: "medium_project_bg.jpg",
            hash: "medium_project_bg_578b15fc21",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 750,
            height: 519,
            size: 14.55,
            path: null,
            url: "/uploads/medium_project_bg_578b15fc21.jpg",
          },
          small: {
            name: "small_project_bg.jpg",
            hash: "small_project_bg_578b15fc21",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 500,
            height: 346,
            size: 5.48,
            path: null,
            url: "/uploads/small_project_bg_578b15fc21.jpg",
          },
        },
        hash: "project_bg_578b15fc21",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 62.59,
        url: "/uploads/project_bg_578b15fc21.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:19:34.416Z",
        updated_at: "2023-11-12T17:19:34.485Z",
      },
      media: null,
      items: [],
      projects: [
        {
          id: 2,
          title: "5 kW Kangoori, Shah Noorani",
          content:
            "This is a 5 kW solar water pumping system installed by SSES on 24th April, 2020. Mr. Sardar Akhtar Mengal (Member of National Assembly, Pakistan) sponsored this project for the poor people of this small village Kangoori, which is located near Shah Noorani Dargah Balochistan. SSES successfully completed this project within two days despite its remote location. All the safety measures were taken and SOPs were strictly followed as this project was installed during the corona pandemic days.",
          subtitle: "SOLAR WATER PUMPING SYSTEM",
          link: "/project-details",
          shown_on_footer: null,
          type: "SOLAR WATER PUMPING SYSTEM",
          parent: "main-board-3",
          slug: "5-k-w-kangoori-shah-noorani",
          excerpt:
            "This is a 5 kW solar water pumping system installed by SSES on 24th April, 2020. Mr. Sardar Akhtar Mengal (Member of National Assembly, Pakistan) sponsored...",
          date: "2020-04-24",
          clients: "Sardar Akhtar Mengal",
          category: "Solar Water Pumping",
          location: "Kangoori Shah Noorani, Balochistan",
          about_project_text: "About This Project",
          project_details_text: "Project Details",
          project_identifier: "Shah Noorani",
          published_at: "2023-11-24T22:36:59.383Z",
          created_at: "2023-11-24T22:34:34.803Z",
          updated_at: "2023-11-30T00:03:49.503Z",
          media: {
            id: 213,
            name: "single-project_1.jpg",
            alternativeText: "",
            caption: "",
            width: 1000,
            height: 408,
            formats: {
              thumbnail: {
                name: "thumbnail_single-project_1.jpg",
                hash: "thumbnail_single_project_1_6bdacf5cce",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 245,
                height: 100,
                size: 7.33,
                path: null,
                url: "/uploads/thumbnail_single_project_1_6bdacf5cce.jpg",
              },
              medium: {
                name: "medium_single-project_1.jpg",
                hash: "medium_single_project_1_6bdacf5cce",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 750,
                height: 306,
                size: 52.27,
                path: null,
                url: "/uploads/medium_single_project_1_6bdacf5cce.jpg",
              },
              small: {
                name: "small_single-project_1.jpg",
                hash: "small_single_project_1_6bdacf5cce",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 500,
                height: 204,
                size: 25.88,
                path: null,
                url: "/uploads/small_single_project_1_6bdacf5cce.jpg",
              },
            },
            hash: "single_project_1_6bdacf5cce",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 81.21,
            url: "/uploads/single_project_1_6bdacf5cce.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:25:46.026Z",
            updated_at: "2023-11-12T17:25:46.215Z",
          },
          background_image: {
            id: 232,
            name: "project-01.jpg",
            alternativeText: "",
            caption: "",
            width: 466,
            height: 466,
            formats: {
              thumbnail: {
                name: "thumbnail_project-01.jpg",
                hash: "thumbnail_project_01_5e3100bcf7",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 156,
                height: 156,
                size: 11.45,
                path: null,
                url: "/uploads/thumbnail_project_01_5e3100bcf7.jpg",
              },
            },
            hash: "project_01_5e3100bcf7",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 107.25,
            url: "/uploads/project_01_5e3100bcf7.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:25:53.782Z",
            updated_at: "2023-11-12T17:25:53.870Z",
          },
        },
      ],
      team: [],
      testimonials: [],
    },
    {
      id: 4,
      title: "Professional Team Member",
      slug: "team",
      subtitle: "Professional Team",
      button_title: null,
      button_link: null,
      published_at: "2023-11-24T23:52:55.461Z",
      created_at: "2023-11-24T23:52:53.313Z",
      updated_at: "2023-11-25T00:08:05.222Z",
      background_image: null,
      media: null,
      items: [],
      projects: [],
      team: [
        {
          id: 1,
          title: "Hassan Jafri",
          subtitle: "CEO/ Managing Director",
          social_link_1: "https://www.facebook.com/hassan.jafri.902/",
          social_link_2: "https://www.linkedin.com/in/hassan-jafri-7a6b171ba/",
          social_link_3:
            "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw",
          published_at: "2023-11-20T00:44:30.241Z",
          created_at: "2023-11-20T00:44:27.241Z",
          updated_at: "2023-11-25T00:38:10.800Z",
          media: {
            id: 281,
            name: "team-member1.jpg",
            alternativeText: "",
            caption: "",
            width: 264,
            height: 261,
            formats: {
              thumbnail: {
                name: "thumbnail_team-member1.jpg",
                hash: "thumbnail_team_member1_38ae96159c",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 158,
                height: 156,
                size: 5.28,
                path: null,
                url: "/uploads/thumbnail_team_member1_38ae96159c.jpg",
              },
            },
            hash: "team_member1_38ae96159c",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 10.29,
            url: "/uploads/team_member1_38ae96159c.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:26:51.428Z",
            updated_at: "2023-11-12T17:26:51.556Z",
          },
        },
        {
          id: 2,
          title: "Abdul Hameed Mengal",
          subtitle: "CEO",
          social_link_1: "https://www.facebook.com/engr.mengal/",
          social_link_2: null,
          social_link_3:
            "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw/",
          published_at: "2023-11-20T00:45:58.300Z",
          created_at: "2023-11-20T00:45:55.398Z",
          updated_at: "2023-11-25T00:39:19.394Z",
          media: {
            id: 283,
            name: "team-member2.jpg",
            alternativeText: "",
            caption: "",
            width: 264,
            height: 261,
            formats: {
              thumbnail: {
                name: "thumbnail_team-member2.jpg",
                hash: "thumbnail_team_member2_09aa77a67c",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 158,
                height: 156,
                size: 6.38,
                path: null,
                url: "/uploads/thumbnail_team_member2_09aa77a67c.jpg",
              },
            },
            hash: "team_member2_09aa77a67c",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 12.35,
            url: "/uploads/team_member2_09aa77a67c.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:26:51.928Z",
            updated_at: "2023-11-12T17:26:52.030Z",
          },
        },
        {
          id: 3,
          title: "Muhammad Usama Nasir",
          subtitle: "Managing Director",
          social_link_1: "https://www.facebook.com/M.UsamaNasir/",
          social_link_2: "https://www.linkedin.com/in/mohammad-usama-518555a6/",
          social_link_3:
            "https://www.youtube.com/channel/UCuY7QJnQaI3u10HwatPCRDw/",
          published_at: "2023-11-20T00:46:54.000Z",
          created_at: "2023-11-20T00:46:51.862Z",
          updated_at: "2023-11-25T00:39:51.879Z",
          media: {
            id: 285,
            name: "team-member3.jpg",
            alternativeText: "",
            caption: "",
            width: 264,
            height: 261,
            formats: {
              thumbnail: {
                name: "thumbnail_team-member3.jpg",
                hash: "thumbnail_team_member3_71e05482de",
                ext: ".jpg",
                mime: "image/jpeg",
                width: 158,
                height: 156,
                size: 5.11,
                path: null,
                url: "/uploads/thumbnail_team_member3_71e05482de.jpg",
              },
            },
            hash: "team_member3_71e05482de",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 10.13,
            url: "/uploads/team_member3_71e05482de.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:26:52.333Z",
            updated_at: "2023-11-12T17:26:52.409Z",
          },
        },
      ],
      testimonials: [],
    },
    {
      id: 5,
      title: "Some of Our Respected Happy Clients Says",
      slug: "testimonials",
      subtitle: "Our Testimonial",
      button_title: null,
      button_link: null,
      published_at: "2023-11-25T20:43:59.782Z",
      created_at: "2023-11-25T20:43:57.358Z",
      updated_at: "2023-11-25T20:48:19.361Z",
      background_image: null,
      media: {
        id: 238,
        name: "project-06.jpg",
        alternativeText: "",
        caption: "",
        width: 466,
        height: 466,
        formats: {
          thumbnail: {
            name: "thumbnail_project-06.jpg",
            hash: "thumbnail_project_06_400ef127cf",
            ext: ".jpg",
            mime: "image/jpeg",
            width: 156,
            height: 156,
            size: 10.41,
            path: null,
            url: "/uploads/thumbnail_project_06_400ef127cf.jpg",
          },
        },
        hash: "project_06_400ef127cf",
        ext: ".jpg",
        mime: "image/jpeg",
        size: 62.96,
        url: "/uploads/project_06_400ef127cf.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        created_at: "2023-11-12T17:25:55.886Z",
        updated_at: "2023-11-12T17:25:55.958Z",
      },
      items: [],
      projects: [],
      team: [],
      testimonials: [
        {
          id: 4,
          client_name: "Owais Zaki",
          designation: "(Area Manager Ideas By Gul Ahmed)",
          message:
            "I had installed the solar power generation system at my home through Sustainable Solar Energy Solutions & have been using it since July 2019. Alhamdulillah very satisfied with the work & the product. Excellent customer service, the team is very supportive & resolves any kind of issues immediately. P.S. The society i am living in has no K.E. connection yet. Solar power is the only source of electricity since I am against the Kunda system.",
          published_at: "2023-11-25T20:41:59.867Z",
          created_at: "2023-11-25T20:41:57.497Z",
          updated_at: "2023-11-26T03:44:25.645Z",
          avatar: null,
        },
        {
          id: 1,
          client_name: "Mr. Azhar Abbas",
          designation: "Head of Facilities Management, Habib University",
          message:
            "This is a young startup and with lot of promise and passion.\n                         Young graduates of alternate energy  have all relevant skills,\n                           techniques  and knowledge of this new emerging discipline. \n                           I recommend fully to their success,  as have seen on my project",
          published_at: "2023-11-25T20:36:00.099Z",
          created_at: "2023-11-25T20:35:57.532Z",
          updated_at: "2023-11-25T20:39:07.835Z",
          avatar: null,
        },
        {
          id: 2,
          client_name: "Yousuf Khan",
          designation: "General Manager (Energy and Engineering)Matiari Group.",
          message:
            "This team of young engineers has impressed me.\n                         In a small span of time they have achieved landmark success. \n                          They are energetic, intelligent, hard working,articulate and \n                          because of this they fix difficult targets and endeavour challenging projects\n                           for themselves, they then work diligently to achieve results\n                            and usually succeed. Their creative and result oriented approach is applaudable. \n                             I am glad to wish these young professionals pronounced success in their carrier.",
          published_at: "2023-11-25T20:39:54.088Z",
          created_at: "2023-11-25T20:39:51.630Z",
          updated_at: "2023-11-25T20:39:54.122Z",
          avatar: null,
        },
        {
          id: 3,
          client_name: "Mr. Imran Qayyum",
          designation: "Owner of Alpha Petroleum Services ( PSO Outlet )",
          message:
            "Sustainable Solar Energy Solution is a wonderful setup with young\n                         and qualified engineers who are experts in their field. I am fully satisfied \n                         with their services.",
          published_at: "2023-11-25T20:41:13.222Z",
          created_at: "2023-11-25T20:41:10.715Z",
          updated_at: "2023-11-25T20:41:13.273Z",
          avatar: {
            id: 131,
            name: "testi_avatar01.png",
            alternativeText: "",
            caption: "",
            width: 80,
            height: 80,
            formats: null,
            hash: "testi_avatar01_17d7b3f77c",
            ext: ".png",
            mime: "image/png",
            size: 5.3,
            url: "/uploads/testi_avatar01_17d7b3f77c.png",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            created_at: "2023-11-12T17:21:38.463Z",
            updated_at: "2023-11-12T17:21:38.532Z",
          },
        },
      ],
    },
  ],
  pageData: {
    id: 1,
    title: null,
    subtitle: null,
    form_title: "Contact With Us",
    form_subtitle: "Send us a message and we' ll respond as soon as possible",
    help_title: "Need Any Help?",
    help_subtitle: "Call us or message and we' ll respond as soon as possible",
    published_at: "2023-11-20T23:06:34.932Z",
    created_at: "2023-11-20T23:06:32.805Z",
    updated_at: "2023-11-20T23:06:34.953Z",
  },
  form: {
    id: 1,
    title: "Contact With Us",
    subtitle: "Send us a message and we' ll respond as soon as possible",
    button_text: "Send Message",
    button_link: null,
    form_id: "contact-form",
    published_at: "2023-12-03T08:14:32.095Z",
    created_at: "2023-12-03T08:14:30.121Z",
    updated_at: "2023-12-03T08:42:46.546Z",
    input_fields: [
      {
        id: 6,
        label: null,
        type: "text",
        placeholder: "First Name",
        required: true,
        hint: null,
        error_message: null,
        form_id: "contact-form",
        published_at: "2023-12-03T08:15:59.491Z",
        created_at: "2023-12-03T08:15:57.240Z",
        updated_at: "2023-12-03T08:15:59.532Z",
      },
      {
        id: 7,
        label: null,
        type: "email",
        placeholder: "Email Address",
        required: true,
        hint: null,
        error_message: null,
        form_id: "contact-form",
        published_at: "2023-12-03T08:16:23.840Z",
        created_at: "2023-12-03T08:16:21.855Z",
        updated_at: "2023-12-03T08:16:23.878Z",
      },
      {
        id: 8,
        label: null,
        type: "text",
        placeholder: "Phone Number",
        required: true,
        hint: null,
        error_message: null,
        form_id: "contact-form",
        published_at: "2023-12-03T08:17:15.367Z",
        created_at: "2023-12-03T08:17:13.259Z",
        updated_at: "2023-12-03T08:17:15.413Z",
      },
      {
        id: 9,
        label: null,
        type: "text",
        placeholder: "Subject",
        required: null,
        hint: null,
        error_message: null,
        form_id: "contact-form",
        published_at: "2023-12-03T08:20:56.147Z",
        created_at: "2023-12-03T08:20:53.647Z",
        updated_at: "2023-12-03T08:21:10.701Z",
      },
      {
        id: 10,
        label: null,
        type: "textarea",
        placeholder: "Your Message here",
        required: null,
        hint: null,
        error_message: null,
        form_id: "contact-form",
        published_at: "2023-12-03T08:36:48.106Z",
        created_at: "2023-12-03T08:36:45.693Z",
        updated_at: "2023-12-03T08:36:48.147Z",
      },
    ],
  },
};
